// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace FuckThis
{
	public partial class WindowContoller : NSWindow
	{
		public WindowContoller (IntPtr handle) : base (handle)
		{
		}
	}
}
